#services:
#  mongodb:
#    image: 'mongo:latest'
#    environment:
#      - 'MONGO_INITDB_DATABASE=mydatabase'
#      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
#      - 'MONGO_INITDB_ROOT_USERNAME=root'
#    ports:
#      - '27017:27017'
services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
#  hellotodayapi:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file:
#      - .env
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod, railway
#    restart: always
#    image: hellotodayapi
#    ports:
#      - '8080:8080'