spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          stream-usage: true

# Railway-specific settings
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Railway WebSocket and Server Configuration
server:
  forward-headers-strategy: native
  port: ${PORT:8080}

# WebSocket configuration for Railway
logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
