spring:
  data:
    mongodb:
      password: bRwHvkHyOQqWMpRaDgmqfhFomOVdFWDu
      username: mongo
      uri: mongodb://mongo:bRwHvkHyOQqWMpRaDgmqfhFomOVdFWDu@mongodb.railway.internal:27017/mydatabase