spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          stream-usage: true

server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never
    include-message: always
  # Railway 환경에서 WebSocket 지원
  forward-headers-strategy: framework

# Railway-specific settings
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
