spring:
  data:
    mongodb:
      password: bRwHvkHyOQqWMpRaDgmqfhFomOVdFWDu
      username: mongo
      uri: mongodb://mongo:bRwHvkHyOQqWMpRaDgmqfhFomOVdFWDu@yamanote.proxy.rlwy.net:53189/mydatabase